### ISSUE TITLE
Geração de dados no início do script precisa ser definido

### ISSUE THREAD

**Issue by euleralencar** [ronissonlucas/Palestra_SQL_Data_Science#1]
Olá Lucas,

O comando `df = gerar_dados(100)` gera erro, pois acredito que ele precisa ser melhor definido. Essa base foi gerada a partir de algum script?

**Comment by ronissonlucas** [comment]
Olá, estava faltando o arquivo `utils.py`, dentro dele você irá encontrar a função que gera os dados sintéticos. Mas é uma função simples e você pode adicionar algum grau maior de complexidade. Tente novamente.

**Comment by euleralencar** [comment]
Perfeito, deu certo Lucas. Valeu!!!
